framework:
  test: true

services:
  _defaults:
    autoconfigure: true
    autowire: true

  CodelyTv\Tests\:
    resource: '../../../../tests'

  # Instance selector
  CodelyTv\Shared\Domain\RandomNumberGenerator: '@CodelyTv\Tests\Shared\Infrastructure\ConstantRandomNumberGenerator'
